# Generated by Django 5.1.5 on 2025-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFiles',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='myfiles')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
