# Generated by Django 5.1.5 on 2025-06-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfiles',
            name='file',
            field=models.FileField(upload_to='Myfiles'),
        ),
    ]
