# Generated by Django 5.1.5 on 2025-07-16 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_file_upload_user_delete_myfiles_file_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='shared_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
