# Generated by Django 5.1.5 on 2025-07-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_file_upload_shared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to='app.user'),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_files', to='app.user'),
        ),
    ]
