# Generated by Django 5.1.5 on 2025-07-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_file_upload_receiver_alter_file_upload_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='receiver',
        ),
        migrations.AddField(
            model_name='file_upload',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='received_files', to='app.user'),
        ),
    ]
