# Generated by Django 5.1.5 on 2025-07-16 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_file_upload_receiver_file_upload_receivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='receivers',
        ),
        migrations.AddField(
            model_name='file_upload',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to='app.user'),
        ),
    ]
