# Generated by Django 5.1.5 on 2025-07-22 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_documentrequest_delete_requireddocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document Request', 'verbose_name_plural': 'Document Requests'},
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed description of the request.'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='from_user',
            field=models.ForeignKey(help_text='User who sent the document request.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='app.user'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('declined', 'Declined')], default='pending', help_text='Current status of the document request.', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the document request.', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='to_user',
            field=models.ForeignKey(help_text='User who received the document request.', on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='app.user'),
        ),
    ]
