# Generated by Django 5.1.5 on 2025-07-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_documentrequest_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentRequest',
        ),
    ]
