# Generated by Django 5.1.5 on 2025-07-23 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_filerequest_requestedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUploadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('file_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_links', to='app.filerequest')),
            ],
        ),
    ]
