# Generated by Django 5.1.5 on 2025-07-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_temporaryuploadlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryUploadLink',
        ),
    ]
