# Generated by Django 5.1.5 on 2025-07-23 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_temporaryuploadlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUploadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('file_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filerequest')),
            ],
        ),
    ]
