# Generated by Django 5.1.5 on 2025-07-23 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_temporaryuploadlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUploadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_in_minutes', models.IntegerField(default=30)),
            ],
        ),
    ]
