# Generated by Django 5.1.5 on 2025-07-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_guestuploadlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuploadlink',
            name='expires_in_minutes',
            field=models.IntegerField(default=100),
        ),
    ]
