# Generated by Django 5.1.5 on 2025-07-23 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_guestuploadlink_expires_in_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_files', to='app.user'),
        ),
    ]
