# Generated by Django 5.1.5 on 2025-07-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_guestuploadlink_expires_in_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
