# Generated by Django 5.1.5 on 2025-07-27 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_filerequest_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuploadlink',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_upload_links', to='app.user'),
        ),
    ]
