# Generated by Django 5.1.5 on 2025-07-27 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_guestuploadlink_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuploadlink',
            name='requester',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='guest_upload_links', to='app.user'),
            preserve_default=False,
        ),
    ]
