# Generated by Django 5.1.5 on 2025-07-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_guestuploadlink_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='guest_uploader_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
