# Generated by Django 5.1.5 on 2025-07-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_documenttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
