# Generated by Django 5.1.5 on 2025-07-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_delete_documenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='file_field',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
