# Generated by Django 5.1.5 on 2025-07-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_documentlist_documentlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentlistitem',
            name='document_list',
        ),
        migrations.DeleteModel(
            name='DocumentList',
        ),
        migrations.DeleteModel(
            name='DocumentListItem',
        ),
    ]
