# Generated by Django 5.1.5 on 2025-07-30 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_documentlist_documentlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedfile',
            name='document_list_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.documentlistitem'),
        ),
    ]
