# Generated by Django 5.1.5 on 2025-08-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_requestedfile_document_list_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedfile',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.file_upload'),
        ),
    ]
