# Generated by Django 5.1.5 on 2025-08-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_requestedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuploadlink',
            name='document_list_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
