# Generated by Django 5.1.5 on 2025-08-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_guestuploadlink_document_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuploadlink',
            name='document_list',
        ),
    ]
