# Generated by Django 5.1.5 on 2025-08-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_guestuploadlink_document_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='document_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.documentlist'),
        ),
    ]
